### ISSUE TITLE
Feature Request: Prop to change floor of either axis

### ISSUE THREAD

**Issue by joesaraceno** [beizhedenglong/rough-charts#1]
If I have data to plot to a line graph with a narrow range, i.e. temperature data, I can not find a way to change the lowest value on the Y Axis from 0. So, in my case I end up with a flat line of values at the top of the graph.

In the source `useChartContext` code I see references to the props userXScale/userYScale, but it appears to take 0 as the bottom range regardless of what is supplied:

```
if (userYScale) {
       userYScale.range([0, contentHeight])
```

If this feature exists, it should be documented. 

All of the storybook pages and examples you show in the repo show 0 as the bottom bound of the Y Axis.

If this feature does not exist, please allow a way pass a preferred yAxis start value into the ChartContext. With a static set of data, the user could trivially determine a suitable bottom value, and pass it in.

Perhaps, fitting the animated style of the project, a squiggly "break" could be used to show the graph's distortion from 0.

**Comment by beizhedenglong** [comment]
@joesaraceno that range function  set the pixel rang in screen. You can  override  the default `scale ` by passing `xScale/yScale` to `ChartProvider`. I added a new [example](https://beizhedenglong.github.io/rough-charts/?path=/story/chartprovider--with-customized-scale) to illustrate this functionality. Please  check it out.
<img width="857" alt="image" src="https://user-images.githubusercontent.com/12963675/66844911-bc557100-efa1-11e9-9225-f07a0c9cb594.png">

**Comment by joesaraceno** [comment]
awesome! thanks for the quick reply. Creating a d3scale by passing in my lower and upper bound seems to be working great.

I would still suggest allowing the user to pass the range directly into the ChartProvider, instead of having to bring in the d3scale library just to create a d3scale object that gets passed in right away anyway.

**Comment by beizhedenglong** [comment]
Different scales in d3-scale have different configurations. Such as log scale/power scale has a `base`/`exponent` config. If we include all these features, it will end up with too many props in `ChartProvider`. To keep API minimal and consistent, maybe it's better to leave the configuration to d3-scale or do you have any good suggestions?

**Comment by honestcomrade** [comment]
I was only thinking of this in the context of a single chart type (time
series line graph). Given that there are many different chart types that
require their own d3scale object type, I can not quickly think of a trivial
way to remedy this without bloating the API, as you pointed out. Thanks for
the quick feedback on this request.
