### ISSUE TITLE
Feature Request: Real graph like YAxis, vertical on x=0

### ISSUE THREAD

**Issue by AndreSteenbergen** [beizhedenglong/rough-charts#10]
Really like this charting library. I would like to have XAxis to behave like the Y axis. ranging from a minus X to a plus X and have ticks equally apart etc. Maybe it is already possible, just don't know how to do that.

**Comment by AndreSteenbergen** [comment]
![image](https://user-images.githubusercontent.com/7676790/82252509-6b4e9680-994f-11ea-9e0e-78b1abbf9309.png)

**Comment by AndreSteenbergen** [comment]
I found the xScale property; I now have this image. Is it possible to move the Y-Axis to be at x = 0

**Comment by AndreSteenbergen** [comment]
![image](https://user-images.githubusercontent.com/7676790/82260582-da32ec00-995d-11ea-9adf-e27ae2dfe998.png)

**Comment by beizhedenglong** [comment]
I added a new prop `startFromX` for positioning  `YAxis`.
https://beizhedenglong.github.io/rough-charts/?path=/docs/yaxis--set-start-from
