### ISSUE TITLE
useful value in Tooltips

### ISSUE THREAD

**Issue by phryneas** [beizhedenglong/rough-charts#2]
Currently, the tooltip always shows the value, but not much additional information. Would it be possible to specify a key that might contain a name to be displayed?

**Comment by beizhedenglong** [comment]
@phryneas I added a new feature for rendering custom tooltip content. Click [this link](https://beizhedenglong.github.io/rough-charts/?path=/docs/tooltip--with-customized-string-content) to see  the details.

<img width="830" alt="image" src="https://user-images.githubusercontent.com/12963675/66845371-7b119100-efa2-11e9-8fd7-8d13613581b1.png">

**Comment by phryneas** [comment]
wonderful, thank you!
