### ISSUE TITLE
Feature Request: restict area to ArcSeries

### ISSUE THREAD

**Issue by phryneas** [beizhedenglong/rough-charts#3]
Hi there,
I have another feature request: right now, I get a LOT of whitespace (I guess space for Axis) when only plotting an ArcSeries.

Is there a simple way to restrict this area?

**Comment by beizhedenglong** [comment]
@phryneas Do you want narrow the space around arcs?. you can pass specific  width, height and margin to `ChartProvider` component.

**Comment by phryneas** [comment]
Argh, I somehow had the impression that only left and top of margin would do something. My bad, sorry!
