### ISSUE TITLE
Feature request: line area chart

### ISSUE THREAD

**Issue by sorodrigo** [beizhedenglong/rough-charts#4]
Love the project!! 😍 
Is there an existing way to make a Area chart such as this one? 
http://recharts.org/en-US/examples/SimpleAreaChart

**Comment by beizhedenglong** [comment]
@sorodrigo I will add this feature soon

**Comment by beizhedenglong** [comment]
@sorodrigo I added a new component called `AreaSeries` for creating basic/stacked  area chart.

Click this [link](https://beizhedenglong.github.io/rough-charts/?path=/docs/areaseries--basic) to see the example.
<img width="794" alt="image" src="https://user-images.githubusercontent.com/12963675/67010106-a1107000-f11f-11e9-8cf9-c0d7cac01b03.png">

**Comment by sorodrigo** [comment]
A-MAZING! Thanks so much, I'll make sure to share you the link when this ends up in prod.
