### ISSUE TITLE
Hosted API

### ISSUE THREAD

**Issue by chrisvxd** [beizhedenglong/rough-charts#8]
Hey @beizhedenglong 👋 Thanks for creating such a beautiful charting library.

I'm looking to convert open source libs into SaaS APIs as part of my work with [saasify.sh](https://saasify.sh) and thought rough-charts would be a great fit.

For example, I'd like to create an API endpoint to render charts like

```
https://api.saasify.sh/1/call/dev/rough-charts@latest/render
```

called with a JSON payload that represents your React usage in a [`react-from-json` format](https://github.com/hydrateio/react-from-json)

```json
{
  "data": [
    { "name": "A", "value": 30 },
    { "name": "B", "value": 90 }
  ],
  "height": 400,
  "children": [
    { "type": "XAxis", "dataKey": "name" },
    { "type": "YAxis" },
    { "type": "LineSeries", "dataKey": "value"}
  ]
}
```

We'd love to offer a rate-limited API and reserve most of the profits for you. As an example, we've also worked on converting sindresorhus' [imagemin](http://imagemin.saasify.sh/) and minimaxir's [stylecloud](http://wordcloud.saasify.sh/) to APIs.

Looking forward to hearing your thoughts! Would also be happy to jump on a quick call to discuss.

**Comment by beizhedenglong** [comment]
Thanks. It sounds interesting and you can convert `rough-charts` into SaaS APIs.

**Comment by chrisvxd** [comment]
Awesome, thanks for the green light @beizhedenglong! I'll keep you posted via this thread.

If you're interested, we also have [an open slack](https://join.slack.com/t/saasify/shared_invite/enQtODAxODA5MzU0NjczLTczOGU3NzNkYTJlMWIwZDkyNjJkOTk3MGEwZThlOWQyNTQxODZjZTExNjAzODJlZDQ3MWM5NWQwMGRiMDcyZTY) where you can reach us more directly.
